language: go

go:
  - 1.2

script:
  - for p in $(go list ./...); do gofmt -w -r "\"$(echo ${p} | sed -e 's/nabeken/crowdmob/')\" -> \"${p}\"" .; done
  - go test -v ./aws/
  - go test -v ./cloudwatch/
  - go test -v ./dynamodb/
  - go test -v ./ec2/
  - go test -v ./elb/
  - go test -v ./iam/
  - go test -v ./s3/
  - go test -v ./sqs/
